# Generated by Django 2.0.3 on 2018-03-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='电影名')),
                ('brief', models.TextField(verbose_name='电影介绍')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
            },
        ),
    ]
