# Generated by Django 2.0.3 on 2018-04-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='create_date',
            field=models.CharField(max_length=30, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='film',
            name='img',
            field=models.CharField(max_length=50, verbose_name='电影图片'),
        ),
        migrations.AlterField(
            model_name='film',
            name='link',
            field=models.CharField(max_length=50, verbose_name='电影链接'),
        ),
        migrations.AlterField(
            model_name='film',
            name='rete',
            field=models.CharField(max_length=5, verbose_name='电影评分'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(max_length=20, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='time',
            field=models.CharField(max_length=100, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='sysconfig',
            name='k',
            field=models.CharField(max_length=20, verbose_name='k参数值'),
        ),
        migrations.AlterField(
            model_name='sysconfig',
            name='random',
            field=models.CharField(max_length=20, verbose_name='随机值'),
        ),
    ]
