# Generated by Django 2.0.3 on 2018-04-02 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='电影名')),
                ('brief', models.TextField(verbose_name='电影介绍')),
                ('rete', models.TextField(verbose_name='电影评分')),
                ('link', models.TextField(verbose_name='电影链接')),
                ('img', models.TextField(verbose_name='电影图片')),
                ('create_date', models.TextField(verbose_name='日期')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.TextField(verbose_name='评分')),
                ('time', models.TextField(verbose_name='时间')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Film', verbose_name='电影')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '评分',
                'verbose_name_plural': '评分',
            },
        ),
        migrations.CreateModel(
            name='Sysconfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k', models.TextField(verbose_name='k参数值')),
                ('random', models.TextField(verbose_name='随机值')),
            ],
            options={
                'verbose_name': '系统参数',
                'verbose_name_plural': '系统参数',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Genres', verbose_name='电影分类'),
        ),
    ]
