# Generated by Django 2.0.3 on 2018-04-04 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20180402_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='rete',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='film',
            name='genres',
        ),
    ]
